name: absensi_kse_qr
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.4.2
  http: ^1.6.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_app_name: ^0.1.1

flutter_app_name:
  name: "Absensi KSE UNS"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/logo-kse-uns.svg
    - assets/images/logo-kse-uns.png
    - assets/images/logo-kse-uns-2.png

dependency_overrides:
  xml: ^6.5.0

